backend:
backend:
  name: github
  repo: younoto14/yeny-gym-site # Change this to your GitHub path
  branch: main # or master

media_folder: "public/images" # Where images will be saved
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json" # You will move your text to this file
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "title", widget: "string"}
          - {label: "Hero Subtitle", name: "subtitle", widget: "text"}
          - {label: "Background Image", name: "image", widget: "image"}
