backend:
  name: github
  repo: younoto14/yeny-gym-site
  branch: main

site_url: https://yeny-gym-site.vercel.app

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "title", widget: "string"}
          - {label: "Hero Subtitle", name: "subtitle", widget: "text"}
          - {label: "Background Image", name: "image", widget: "image"}
